### ISSUE TITLE
Any way to convert discord.embed object to an an embed that can be inserted using add_embed()?

### ISSUE THREAD

**Issue by bagfaced** [lovvskillz/python-discord-webhook#105]
Pulling discord messages using discord.py and the only instance that can't be handled easily is embeds. Inserting them as is (a Discord.embed object) produces a error Object of type Embed is not json serializable. Is there any quick way I can convert it, or a work-around to call that will add it? 

Traceback (most recent call last):
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 301, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\17167\Desktop\DiscordBot\kingdom_read.py", line 32, in on_message
    await send_webhook(message, shitcoin_alpha)
  File "c:\Users\17167\Desktop\DiscordBot\kingdom_read.py", line 52, in send_webhook
    await webhook.execute()
  File "C:\Python310\lib\site-packages\discord_webhook\async_webhook.py", line 71, in execute   
    response = await self.api_post_request(url)
  File "C:\Python310\lib\site-packages\discord_webhook\async_webhook.py", line 51, in api_post_request
    response = await client.post(url, json=self.json,
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_client.py", line 1514, in request
    request = self.build_request(
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_client.py", line 356, in build_request
    return Request(
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_models.py", line 336, in __init__
    headers, stream = encode_request(content, data, files, json)
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_content.py", line 214, in encode_request
    return encode_json(json)
  File "C:\Users\17167\AppData\Roaming\Python\Python310\site-packages\httpx\_content.py", line 177, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Embed is not JSON serializable

![Screenshot 2022-09-24 125817](https://user-images.githubusercontent.com/114305608/192109905-20cc1348-ce91-49e3-8de6-dd83f46cdd4e.png)

**Comment by lovvskillz** [comment]
This would be a nice feature for the future. In the meantime you could look into the [add_embed()](https://github.com/lovvskillz/python-discord-webhook/blob/master/discord_webhook/webhook.py#L303) method.
`embeds` expects a list of dicts or `embed.__dict__`s if it's an instance of `DiscordEmbed`. So you should convert `message.embeds` to a list of dicts. I hope this helps you.
