### ISSUE TITLE
JSON Decode Error when executing webhook

### ISSUE THREAD

**Issue by Column01** [lovvskillz/python-discord-webhook#130]
Hey there,
I've written some simple code to use this library to send a webhook to a channel. Despite this, I get a JSON Decode error as a response to trying to execute the webhook even if I'm doing the most basic thing such as sending the content `test`

Here is the traceback:
```
Traceback (most recent call last):
  File "REDACTED", line 65, in <module>
    scan(properties)
  File "REDACTED", line 50, in scan
    webhook.execute()
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_webhook\webhook.py", line 475, in execute
    response_content = json.loads(response.content.decode("utf-8"))
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Column01** [comment]
I've printed the `response.content.decode("utf-8")` line and it's empty so that would be the issue. No idea whats happening there, but the response is empty from discord

**Comment by Column01** [comment]
I've reached out to discord on twitter asking if there are issues on their end, will update if I get a reply

**Comment by Column01** [comment]
Ignoring the contents of the reply (and commenting out the offending code) results in no message posted on discord so I believe this to be an issue on their end?

**Comment by Column01** [comment]
All good, i figured it out. I had the wrong URL being put into the webhook LOL

**Comment by daviddwlee84** [comment]
I got same error [`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`](https://github.com/lovvskillz/python-discord-webhook/blob/64e5fd52c8d171442762a793c224d983a4202251/discord_webhook/webhook.py#L460C9-L460C72)
But the root cause shows like this in log:
```txt
Webhook status code 502: 
ERROR:root:Expecting value: line 1 column 1 (char 0)
```
https://github.com/lovvskillz/python-discord-webhook/blob/64e5fd52c8d171442762a793c224d983a4202251/discord_webhook/webhook.py#L438-L465

I think this makes error message a little bit misleading (harder to debug)
