### ISSUE TITLE
Change avatar

### ISSUE THREAD

**Issue by yeti2006** [lovvskillz/python-discord-webhook#46]
How do i change the avatar of the webhook, passing in avatar `kwarg `or `avatar_url` doesn't work. How do I fix this?

```
Traceback (most recent call last):
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\Senuka\Documents\fearless\cogs\mod.py", line 49, in hey
    response = webhook.execute()
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\discord_webhook\webhook.py", line 119, in execute
    response = requests.post(url, json=self.json, proxies=self.proxies, params={'wait':True})
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\__init__.py", line 395, in dumps
    return _default_encoder.encode(obj)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\encoder.py", line 298, in encode
    chunks = list(chunks)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict        
    for chunk in chunks:
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\encoder.py", line 716, in _iterencode
    o = _default(o)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\simplejson\encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type Asset is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\users\senuka\appdata\local\programs\python\python38-32\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Object of type Asset is not JSON serializable
```

**Comment by Larkify** [comment]
For me, it's just like...
`webhook = DiscordWebhook(url="webhook_url", username="name", avatar_url="url")`
