### ISSUE TITLE
Webhook stops transmitting data after some time

### ISSUE THREAD

**Issue by r1bnc** [lovvskillz/python-discord-webhook#51]
The webhook stops transmitting data to Discord after a while. It happened thrice now, the first one happened after the script has been running for 12 hours, the second one the script is running for 9 hrs, and now after  7 hrs.

The output is just stuck to: 
```
Uploaded: [ last data in discord ]
```
And the data at discord channel shows: `last data in discord`.
No exceptions have been triggered.

I have the excerpt of the script, more info can be found on my gitlab with the project entitled: `chat-uploader-discord-webhook`.  Beware it's not pretty and doesn't follow PEP8.
```
# tail a log file
# sleep_time is default to 1
# chat_message is the one being fetched from a log file
# VERBOSE is set to True
                time.sleep(sleep_time)
                webhook = DiscordWebhook(url=webhookurl, content=chat_message)
                webhook_execute = webhook.execute()

                # Credits: https://github.com/novasz @ https://github.com/lovvskillz/python-discord-webhook/issues/47
                # Check if webhook response is 200/204
                if webhook_execute.status_code in [200, 204]:
                    if VERBOSE:
                        print("Uploaded: [" + chat_message + "]\n")

                # We are being rate limited :(
                if webhook_execute.status_code == 429:
                    errors = json.loads(webhook_execute.content.decode('utf-8'))
                    wh_sleep = (int(errors['retry_after']) / 1000) + 0.15
                    print("Webhook rate limited: sleeping for " + str(wh_sleep) + " seconds...")
                    # Sleep
                    time.sleep(wh_sleep)
                    # Upload rate limit hit message, discard other messages
                    webhook = DiscordWebhook(url=webhookurl, content=rate_limit_message)
                    webhook_execute = webhook.execute()
                    if webhook_execute.status_code in [200, 204]:
                        if VERBOSE:
                            print("Notify Ratelimit was hit\n")
                    # hmm add if 429 here?
```
I will update the script later, or maybe just add another script that will terminate the python script after a set time  interval and restart it.

Please confirm whether others can reproduce this problem or its just my code problem. Thanks.

**Comment by r1bnc** [comment]
I pressed Ctrl+C and this is the output:
```
^CTraceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./chat-uploader-discord-webhook.py", line 92, in <module>
   if upload:
  File "/home/user/.local/lib/python3.7/site-packages/discord_webhook/webhook.py", line 142, in execute
   response = requests.post(url, json=self.json, proxies=self.proxies, params={'wait': True})
File "/home/user/.local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
   chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

```

Now im gonna try to set the verbose logging https://github.com/lovvskillz/python-discord-webhook/issues/23

**Comment by r1bnc** [comment]
UPDATE: This issue happens when you lost internet connection, but it doesnt display errors.

**Comment by novasz** [comment]
Have you found a fix for this since?

**Comment by r1bnc** [comment]
The quick fix that I thought of is to make an external script to restart the python script, but of course this may result in some data not being uploaded to discord (ex. if time sensitive like chats are uploaded).

From my observation, the script stops whenever you lose internet connection. If you have a stable internet connection, this may not be a problem to you.

**Comment by vremes** [comment]
Hey @r1bnc , timeout for requests has been added to `DiscordWebhook`, can you test if that fixes the issue?

This change has not been published to pypi yet, so you have to install the package using one of the following commands:
```
pip3 install git+https://github.com/lovvskillz/python-discord-webhook.git

pip install git+https://github.com/lovvskillz/python-discord-webhook.git
````

This pull request includes an example on how to use the `timeout` parameter #49

**Comment by r1bnc** [comment]
Hi @vremes,

Thanks for informing me about the pull request, I will try this and monitor through the entire day. Currently busy at things but I will do my best to get back to you.

**Comment by r1bnc** [comment]
UPDATE: The pull request worked! :D I now don't need external script to restart the non responsive python script.
