### ISSUE TITLE
It works only once, after repeating it in a loop this happens the second time: Failed to parse...

### ISSUE THREAD

**Issue by dorian9007** [lovvskillz/python-discord-webhook#56]
raceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/url.py", line 234, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: //<discord_webhook.webhook.DiscordWebhook object at 0x102b4ad90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dorianvoka/Desktop/telegram.py", line 29, in <module>
    response = webhook.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord_webhook/webhook.py", line 144, in execute
    response = requests.post(url, json=self.json, proxies=self.proxies, params={'wait': True}, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: //<discord_webhook.webhook.DiscordWebhook object at 0x102b4ad90>

**Comment by lovvskillz** [comment]
It looks more as if the URL is the problem and not the loop:
`Failed to parse: //<discord_webhook.webhook.DiscordWebhook object at 0x102b4ad90>`
Did you accidentally set the webhook object as the URL instead of a normal string?

**Comment by dorian9007** [comment]
Lol komme auch aus Deutschland. Aber hier mal für alle folgenden die englisch sprechen: 

Yes it works. Thank you. I actually put the URL into a var at the top of my code. Somehow it works now! Thank you!
