### ISSUE TITLE
webhook.delete(sent_webhook) raise AssertionError

### ISSUE THREAD

**Issue by lf2a** [lovvskillz/python-discord-webhook#98]
When i execute this example:

```python
from discord_webhook import DiscordWebhook
from time import sleep

webhook = DiscordWebhook(url=[URL], content='Webhook Content')
sent_webhook = webhook.execute()
sleep(10)
webhook.delete(sent_webhook)
```

I receive this error:
```python
Traceback (most recent call last):
  File "/media/luiz/Dados/dev/example.py", line 77, in <module>
    webhook.delete(sent_webhook)
  File "/media/luiz/Dados/dev/venv/lib/python3.8/site-packages/discord_webhook/webhook.py", line 507, in delete
    assert isinstance(webhook.content, str)
AssertionError
```
requirements.txt
`discord-webhook==0.16.2 `

**Comment by lovvskillz** [comment]
fixed in 0.16.3
